"""Create ticket container(upd)

Revision ID: 219c78b9861e
Revises: 89a4c0bbffdc
Create Date: 2025-05-13 18:31:56.977843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219c78b9861e'
down_revision: Union[str, None] = '89a4c0bbffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticketcontainers',
    sa.Column('proxmox_node', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(), server_default='', nullable=False),
    sa.Column('closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rom_bytes', sa.BigInteger(), nullable=False),
    sa.Column('ram_bytes', sa.BigInteger(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticketcontainers_id'), 'ticketcontainers', ['id'], unique=False)
    op.create_index(op.f('ix_ticketcontainers_name'), 'ticketcontainers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketcontainers_name'), table_name='ticketcontainers')
    op.drop_index(op.f('ix_ticketcontainers_id'), table_name='ticketcontainers')
    op.drop_table('ticketcontainers')
    # ### end Alembic commands ###
