"""Create tg user. upd v2

Revision ID: 561c978d6c59
Revises: dd21611b4855
Create Date: 2025-05-19 21:23:53.221723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561c978d6c59'
down_revision: Union[str, None] = 'dd21611b4855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'chat_id')
    # ### end Alembic commands ###
