"""tg user. upd v4

Revision ID: 571b74c4eb67
Revises: cc8d1d30ddae
Create Date: 2025-05-20 20:16:54.416674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571b74c4eb67'
down_revision: Union[str, None] = 'cc8d1d30ddae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'is_superuser')
    # ### end Alembic commands ###
