"""tg user. upd v5

Revision ID: 603a0c04ee47
Revises: 571b74c4eb67
Create Date: 2025-05-20 20:47:06.167420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603a0c04ee47'
down_revision: Union[str, None] = '571b74c4eb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tgusers', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tgusers', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(None, 'tgusers', ['user_id'])
    op.create_foreign_key(None, 'tgusers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tgusers', type_='foreignkey')
    op.drop_constraint(None, 'tgusers', type_='unique')
    op.alter_column('tgusers', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tgusers', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
