"""tg user. upd v7

Revision ID: 79b169d87c71
Revises: 7d579a90e689
Create Date: 2025-05-20 20:48:26.647772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b169d87c71'
down_revision: Union[str, None] = '7d579a90e689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgusers',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tgusers_id'), 'tgusers', ['id'], unique=False)
    op.create_index(op.f('ix_tgusers_is_deleted'), 'tgusers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tgusers_username'), 'tgusers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tgusers_username'), table_name='tgusers')
    op.drop_index(op.f('ix_tgusers_is_deleted'), table_name='tgusers')
    op.drop_index(op.f('ix_tgusers_id'), table_name='tgusers')
    op.drop_table('tgusers')
    # ### end Alembic commands ###
